/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Control.Paciente;
import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.String;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractListModel;
import javax.swing.DefaultListModel;
import javax.swing.GroupLayout;

/**
 *
 * @author carlos.diniz
 */
public class ListaDePacientes extends javax.swing.JPanel {
    public List<Paciente> pacientes;
    public Paciente paciente1 = new Paciente("carlos", "08/12/1996", "43996683272", "1234567890123");

    /**
     * Creates new form ListaDePacientes
     */
    public ListaDePacientes() {
        initComponents();
        IniciaListaPacientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        listaPaciente = new javax.swing.JList<>();
        Pacientes = new javax.swing.JLabel();
        buttonNovaConsulta = new javax.swing.JButton();

        listaPaciente.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaPaciente);

        Pacientes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Pacientes.setText("Consultas");

        buttonNovaConsulta.setText("Nova Consulta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Pacientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                        .addComponent(buttonNovaConsulta))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pacientes)
                    .addComponent(buttonNovaConsulta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     */
    public void IniciaListaPacientes(){
        pacientes.add(paciente1);
        String[] teste = null;
        DefaultListModel model = new DefaultListModel();
        for(int i = 0; i<pacientes.size(); i++ ){
            teste[i]= pacientes.get(i).nome;
        }
        model.addElement("Carlos");
        listaPaciente.setModel(model);
    }

    

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pacientes;
    private javax.swing.JButton buttonNovaConsulta;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaPaciente;
    // End of variables declaration//GEN-END:variables
}
